insert into events (athlete_id, caption, media_url, category) values (35, 'Which book should I read before my next competition?', 'http://dummyimage.com/107x100.png/ff4444/ffffff', 'poll'),
(4, 'What should be my next touchdown celebration?', 'http://dummyimage.com/147x100.png/5fa2dd/ffffff', 'poll'),
(24, 'Which cause should I donate to next?', 'http://dummyimage.com/118x100.png/ff4444/ffffff', 'poll'),
(18, 'Which city should I visit for my next game?', 'http://dummyimage.com/203x100.png/dddddd/000000', 'poll'),
(33, 'Help me choose my next charity to support!', 'http://dummyimage.com/241x100.png/5fa2dd/ffffff', 'poll'),
(37, 'Help me choose my next charity to support!', 'http://dummyimage.com/244x100.png/cc0000/ffffff', 'poll'),
(37, 'Which charity should I partner with for my next fundraiser?', 'http://dummyimage.com/246x100.png/5fa2dd/ffffff', 'poll'),
(15, 'What should be my next touchdown celebration?', 'http://dummyimage.com/248x100.png/cc0000/ffffff', 'poll'),
(24, 'Which workout should I do for my next training session?', 'http://dummyimage.com/133x100.png/ff4444/ffffff', 'poll'),
(18, 'Which book should I read before my next competition?', 'http://dummyimage.com/188x100.png/ff4444/ffffff', 'poll'),
(37, 'Which book should I read before my next competition?', 'http://dummyimage.com/168x100.png/ff4444/ffffff', 'poll'),
(9, 'Which book should I read before my next competition?', 'http://dummyimage.com/148x100.png/5fa2dd/ffffff', 'poll'),
(32, 'Which workout should I do for my next training session?', 'http://dummyimage.com/219x100.png/cc0000/ffffff', 'poll'),
(6, 'Help me choose my next charity to support!', 'http://dummyimage.com/193x100.png/cc0000/ffffff', 'poll'),
(37, 'Help me choose my next charity to support!', 'http://dummyimage.com/154x100.png/5fa2dd/ffffff', 'poll'),
(27, 'Which charity should I partner with for my next fundraiser?', 'http://dummyimage.com/155x100.png/ff4444/ffffff', 'poll'),
(22, 'Which charity should I partner with for my next fundraiser?', 'http://dummyimage.com/137x100.png/5fa2dd/ffffff', 'poll'),
(20, 'Which workout should I do for my next training session?', 'http://dummyimage.com/196x100.png/cc0000/ffffff', 'poll'),
(12, 'Which city should I visit for my next game?', 'http://dummyimage.com/212x100.png/cc0000/ffffff', 'poll'),
(9, 'Which book should I read before my next competition?', 'http://dummyimage.com/202x100.png/ff4444/ffffff', 'poll'),
(42, 'Which city should I visit for my next game?', 'http://dummyimage.com/105x100.png/5fa2dd/ffffff', 'poll'),
(14, 'Which city should I visit for my next game?', 'http://dummyimage.com/162x100.png/cc0000/ffffff', 'poll'),
(10, 'Which sports gear should I wear for my next game?', 'http://dummyimage.com/154x100.png/dddddd/000000', 'poll'),
(10, 'Help me choose my next charity to support!', 'http://dummyimage.com/123x100.png/cc0000/ffffff', 'poll'),
(36, 'What should be my next touchdown celebration?', 'http://dummyimage.com/235x100.png/cc0000/ffffff', 'poll'),
(25, 'Which pre-game meal should I eat before my next match?', 'http://dummyimage.com/159x100.png/dddddd/000000', 'poll'),
(20, 'Which workout should I do for my next training session?', 'http://dummyimage.com/104x100.png/cc0000/ffffff', 'poll'),
(38, 'Which music should I listen to before my next match?', 'http://dummyimage.com/100x100.png/5fa2dd/ffffff', 'poll'),
(4, 'Which workout should I do for my next training session?', 'http://dummyimage.com/168x100.png/5fa2dd/ffffff', 'poll'),
(30, 'Help me choose my next charity to support!', 'http://dummyimage.com/193x100.png/dddddd/000000', 'poll'),
(18, 'Which book should I read before my next competition?', 'http://dummyimage.com/219x100.png/5fa2dd/ffffff', 'poll'),
(36, 'Which sports gear should I wear for my next game?', 'http://dummyimage.com/195x100.png/5fa2dd/ffffff', 'poll'),
(34, 'Which city should I visit for my next game?', 'http://dummyimage.com/130x100.png/cc0000/ffffff', 'poll'),
(40, 'Which charity should I partner with for my next fundraiser?', 'http://dummyimage.com/112x100.png/ff4444/ffffff', 'poll'),
(13, 'Which cause should I donate to next?', 'http://dummyimage.com/133x100.png/5fa2dd/ffffff', 'poll'),
(31, 'Which book should I read before my next competition?', 'http://dummyimage.com/246x100.png/dddddd/000000', 'poll'),
(24, 'What should be my next touchdown celebration?', 'http://dummyimage.com/184x100.png/5fa2dd/ffffff', 'poll'),
(8, 'Which cause should I donate to next?', 'http://dummyimage.com/157x100.png/cc0000/ffffff', 'poll'),
(5, 'Which book should I read before my next competition?', 'http://dummyimage.com/209x100.png/5fa2dd/ffffff', 'poll'),
(6, 'Which workout should I do for my next training session?', 'http://dummyimage.com/145x100.png/dddddd/000000', 'poll'),
(11, 'Help me choose my next charity to support!', 'http://dummyimage.com/186x100.png/dddddd/000000', 'poll'),
(26, 'Which city should I visit for my next game?', 'http://dummyimage.com/154x100.png/dddddd/000000', 'poll'),
(9, 'Which sports gear should I wear for my next game?', 'http://dummyimage.com/182x100.png/cc0000/ffffff', 'poll'),
(35, 'Which workout should I do for my next training session?', 'http://dummyimage.com/233x100.png/dddddd/000000', 'poll'),
(31, 'Which charity should I partner with for my next fundraiser?', 'http://dummyimage.com/180x100.png/5fa2dd/ffffff', 'poll'),
(16, 'Which music should I listen to before my next match?', 'http://dummyimage.com/172x100.png/dddddd/000000', 'poll'),
(39, 'What should be my next touchdown celebration?', 'http://dummyimage.com/180x100.png/ff4444/ffffff', 'poll'),
(18, 'Which cause should I donate to next?', 'http://dummyimage.com/109x100.png/dddddd/000000', 'poll'),
(32, 'Which music should I listen to before my next match?', 'http://dummyimage.com/118x100.png/5fa2dd/ffffff', 'poll'),
(3, 'Which city should I visit for my next game?', 'http://dummyimage.com/154x100.png/cc0000/ffffff', 'poll');
