insert into events (athlete_id, caption, media_url, category) values (4, 'Training hard every day to reach my goals. Can''t wait to see what this season brings! #motivation #training #athlete', 'http://dummyimage.com/228x100.png/dddddd/000000', 'post'),
(2, 'Excited to share my journey with all of you. Follow along for behind-the-scenes looks at my training and competitions! #athlete #journey #training', 'http://dummyimage.com/107x100.png/5fa2dd/ffffff', 'post'),
(21, 'Honored to be named MVP of the game. Couldn''t have done it without my amazing teammates. #teamwork #athlete #MVP', 'http://dummyimage.com/151x100.png/ff4444/ffffff', 'post'),
(38, 'Just finished an intense workout and feeling stronger than ever. Ready to take on the competition! #fitness #motivation #athlete', 'http://dummyimage.com/161x100.png/cc0000/ffffff', 'post'),
(36, 'Excited to share my journey with all of you. Follow along for behind-the-scenes looks at my training and competitions! #athlete #journey #training', 'http://dummyimage.com/249x100.png/dddddd/000000', 'post'),
(27, 'Joining a new club and ready to make some big moves. Can''t wait to see what we can accomplish together! #newclub #athlete #teamwork', 'http://dummyimage.com/135x100.png/5fa2dd/ffffff', 'post'),
(13, 'Training hard every day to reach my goals. Can''t wait to see what this season brings! #motivation #training #athlete', 'http://dummyimage.com/169x100.png/5fa2dd/ffffff', 'post'),
(22, 'Thrilled to be joining the XYZ team! Looking forward to working with such a talented group of athletes. #newteam #athlete #excited', 'http://dummyimage.com/210x100.png/ff4444/ffffff', 'post'),
(40, 'Excited to share my journey with all of you. Follow along for behind-the-scenes looks at my training and competitions! #athlete #journey #training', 'http://dummyimage.com/228x100.png/5fa2dd/ffffff', 'post'),
(37, 'Just finished an intense workout and feeling stronger than ever. Ready to take on the competition! #fitness #motivation #athlete', 'http://dummyimage.com/135x100.png/dddddd/000000', 'post'),
(2, 'Just finished an intense workout and feeling stronger than ever. Ready to take on the competition! #fitness #motivation #athlete', 'http://dummyimage.com/104x100.png/cc0000/ffffff', 'post'),
(26, 'Excited to announce my new partnership with XYZ brand! Can''t wait to see what the future holds. #sponsored #athlete #newbeginnings', 'http://dummyimage.com/199x100.png/dddddd/000000', 'post'),
(36, 'Excited to announce my new partnership with XYZ brand! Can''t wait to see what the future holds. #sponsored #athlete #newbeginnings', 'http://dummyimage.com/250x100.png/cc0000/ffffff', 'post'),
(29, 'Just finished an intense workout and feeling stronger than ever. Ready to take on the competition! #fitness #motivation #athlete', 'http://dummyimage.com/242x100.png/cc0000/ffffff', 'post'),
(38, 'Honored to be named MVP of the game. Couldn''t have done it without my amazing teammates. #teamwork #athlete #MVP', 'http://dummyimage.com/211x100.png/dddddd/000000', 'post'),
(1, 'Excited to announce my new partnership with XYZ brand! Can''t wait to see what the future holds. #sponsored #athlete #newbeginnings', 'http://dummyimage.com/119x100.png/cc0000/ffffff', 'post'),
(24, 'Big news! I''ll be competing in the XYZ championship next month. Time to bring my A-game! #competition #athlete #championship', 'http://dummyimage.com/199x100.png/cc0000/ffffff', 'post'),
(7, 'Training hard every day to reach my goals. Can''t wait to see what this season brings! #motivation #training #athlete', 'http://dummyimage.com/249x100.png/5fa2dd/ffffff', 'post'),
(32, 'Excited to announce my new partnership with XYZ brand! Can''t wait to see what the future holds. #sponsored #athlete #newbeginnings', 'http://dummyimage.com/102x100.png/ff4444/ffffff', 'post'),
(42, 'Just finished an intense workout and feeling stronger than ever. Ready to take on the competition! #fitness #motivation #athlete', 'http://dummyimage.com/236x100.png/ff4444/ffffff', 'post'),
(3, 'Joining a new club and ready to make some big moves. Can''t wait to see what we can accomplish together! #newclub #athlete #teamwork', 'http://dummyimage.com/180x100.png/ff4444/ffffff', 'post'),
(7, 'Just finished an intense workout and feeling stronger than ever. Ready to take on the competition! #fitness #motivation #athlete', 'http://dummyimage.com/240x100.png/5fa2dd/ffffff', 'post'),
(16, 'Big news! I''ll be competing in the XYZ championship next month. Time to bring my A-game! #competition #athlete #championship', 'http://dummyimage.com/145x100.png/5fa2dd/ffffff', 'post'),
(28, 'Honored to be named MVP of the game. Couldn''t have done it without my amazing teammates. #teamwork #athlete #MVP', 'http://dummyimage.com/230x100.png/5fa2dd/ffffff', 'post'),
(16, 'Big news! I''ll be competing in the XYZ championship next month. Time to bring my A-game! #competition #athlete #championship', 'http://dummyimage.com/239x100.png/dddddd/000000', 'post'),
(29, 'Just finished an intense workout and feeling stronger than ever. Ready to take on the competition! #fitness #motivation #athlete', 'http://dummyimage.com/151x100.png/ff4444/ffffff', 'post'),
(11, 'Big news! I''ll be competing in the XYZ championship next month. Time to bring my A-game! #competition #athlete #championship', 'http://dummyimage.com/159x100.png/cc0000/ffffff', 'post'),
(17, 'Training hard every day to reach my goals. Can''t wait to see what this season brings! #motivation #training #athlete', 'http://dummyimage.com/215x100.png/cc0000/ffffff', 'post'),
(40, 'Just finished an intense workout and feeling stronger than ever. Ready to take on the competition! #fitness #motivation #athlete', 'http://dummyimage.com/142x100.png/5fa2dd/ffffff', 'post'),
(35, 'Joining a new club and ready to make some big moves. Can''t wait to see what we can accomplish together! #newclub #athlete #teamwork', 'http://dummyimage.com/138x100.png/5fa2dd/ffffff', 'post'),
(21, 'Big news! I''ll be competing in the XYZ championship next month. Time to bring my A-game! #competition #athlete #championship', 'http://dummyimage.com/126x100.png/dddddd/000000', 'post'),
(7, 'Honored to be named MVP of the game. Couldn''t have done it without my amazing teammates. #teamwork #athlete #MVP', 'http://dummyimage.com/129x100.png/cc0000/ffffff', 'post'),
(27, 'Honored to be named MVP of the game. Couldn''t have done it without my amazing teammates. #teamwork #athlete #MVP', 'http://dummyimage.com/147x100.png/ff4444/ffffff', 'post'),
(41, 'Excited to announce my new partnership with XYZ brand! Can''t wait to see what the future holds. #sponsored #athlete #newbeginnings', 'http://dummyimage.com/192x100.png/ff4444/ffffff', 'post'),
(1, 'Excited to share my journey with all of you. Follow along for behind-the-scenes looks at my training and competitions! #athlete #journey #training', 'http://dummyimage.com/147x100.png/ff4444/ffffff', 'post'),
(33, 'Training hard every day to reach my goals. Can''t wait to see what this season brings! #motivation #training #athlete', 'http://dummyimage.com/249x100.png/dddddd/000000', 'post'),
(17, 'Thrilled to be joining the XYZ team! Looking forward to working with such a talented group of athletes. #newteam #athlete #excited', 'http://dummyimage.com/233x100.png/5fa2dd/ffffff', 'post'),
(42, 'Excited to share my journey with all of you. Follow along for behind-the-scenes looks at my training and competitions! #athlete #journey #training', 'http://dummyimage.com/166x100.png/dddddd/000000', 'post'),
(29, 'Excited to share my journey with all of you. Follow along for behind-the-scenes looks at my training and competitions! #athlete #journey #training', 'http://dummyimage.com/233x100.png/cc0000/ffffff', 'post'),
(12, 'Joining a new club and ready to make some big moves. Can''t wait to see what we can accomplish together! #newclub #athlete #teamwork', 'http://dummyimage.com/146x100.png/cc0000/ffffff', 'post'),
(9, 'Training hard every day to reach my goals. Can''t wait to see what this season brings! #motivation #training #athlete', 'http://dummyimage.com/218x100.png/ff4444/ffffff', 'post'),
(37, 'Honored to be named MVP of the game. Couldn''t have done it without my amazing teammates. #teamwork #athlete #MVP', 'http://dummyimage.com/207x100.png/dddddd/000000', 'post'),
(11, 'Excited to announce my new partnership with XYZ brand! Can''t wait to see what the future holds. #sponsored #athlete #newbeginnings', 'http://dummyimage.com/213x100.png/dddddd/000000', 'post'),
(29, 'Joining a new club and ready to make some big moves. Can''t wait to see what we can accomplish together! #newclub #athlete #teamwork', 'http://dummyimage.com/125x100.png/ff4444/ffffff', 'post'),
(35, 'Training hard every day to reach my goals. Can''t wait to see what this season brings! #motivation #training #athlete', 'http://dummyimage.com/143x100.png/5fa2dd/ffffff', 'post'),
(21, 'Big news! I''ll be competing in the XYZ championship next month. Time to bring my A-game! #competition #athlete #championship', 'http://dummyimage.com/188x100.png/cc0000/ffffff', 'post'),
(11, 'Training hard every day to reach my goals. Can''t wait to see what this season brings! #motivation #training #athlete', 'http://dummyimage.com/203x100.png/dddddd/000000', 'post'),
(8, 'Training hard every day to reach my goals. Can''t wait to see what this season brings! #motivation #training #athlete', 'http://dummyimage.com/198x100.png/cc0000/ffffff', 'post'),
(14, 'Excited to share my journey with all of you. Follow along for behind-the-scenes looks at my training and competitions! #athlete #journey #training', 'http://dummyimage.com/120x100.png/ff4444/ffffff', 'post'),
(16, 'Training hard every day to reach my goals. Can''t wait to see what this season brings! #motivation #training #athlete', 'http://dummyimage.com/174x100.png/5fa2dd/ffffff', 'post');
